### PR TITLE
Creation of error safe memory allocation functions

### LINKED ISSUE #289: Create safe memory allocation and deallocation wrapper function
## Description
As i have seen in many more repositories, developers do not use any memory management functions by it self. These memory management functions are commonly used inside wrappers that handled error problems.

So I propose a change for the `malloc` calls to a method like:

```
void *xmalloc(size_t size)
{
   void *p;

   p = malloc (size);
   if (!p) {
      perror("xmalloc");
      exit (EXIT_FAILURE);
   }

   return p;
}
```

It makes it simpler for developers to allocate needed memory and prevents the possibility to forget about treating memory allocation common errors.

## Additional content
The same version of calloc, realloc and free can be done inside this same issue.

### LINKED ISSUE #298: Snake doesn't change directions
## Bug description
Snake doesn't change directions.

## Steps to Reproduce
1. Go to the gameplay scene
2. Hold any directional button for some seconds
3. Try to immediately change the snake direction
4. See the bug

## What the expected behavior should've been
If the player hold a button (and a lot of people do this), the snake should 
change his direction immediately when the player press any other direction

## Additional context
It's probably related to fflush(NEED) need, like the #191  issue. 

#

### PR DESCRIPTION
**Pull request by joaofavoretti**
Fixes #289 .

This PR proposes the following changes:
- Creation of xmalloc, xcalloc and xrealloc functions that check if the returned pointer was NULL and exits the program if that was the case
- Replacing all the malloc and realloc calls already there to use the new error safe functions.

### CODE REVIEW

**Comment by henriquesqs** [comment]
Nice feature to have. LG!

**Comment by mathmorfose** [comment]
Very interesting feature!

**Comment by JulioEO** [comment]
Is this closing the correct issue? #298 does not seem to be related to your pull request.

**Comment by mvellosa** [comment]
> Is this closing the correct issue? #298 does not seem to be related to your pull request.

Probably just a typo in the PR text, as the correct issue (#289) was correctly used as the PR and Branch name.

**Review by lucasvianav — APPROVED** [review]

**Review by lucasvianav — CHANGES_REQUESTED** [review]
It'd be good to add a more descriptive title to the PR and correct the issue name in the description (as others have stated above), so it won't close the wrong one

**Comment by joaofavoretti** [comment]
Thank you very much guys. I really havent checked the issue number. I think it should be alright now.

**Review by lucasvianav — APPROVED** [review]
Nice!

**Review by APMedrado — APPROVED** [review]
Great feature!

**Pull request merged**
