### PR TITLE
Add security policy.

### LINKED ISSUE #293: Add security policy
We should add a security policy so contributors outside this project knows how to report any security issue.

### PR DESCRIPTION
**Pull request by henriquesqs**
Fixes #293 .

This PR proposes the following changes:
- Add security policy

### CODE REVIEW

**Review by fernandovgs — DISMISSED** [review]
LGTM!

**Review by fernandovgs — CHANGES_REQUESTED** [review]
Could you please place this new doc under the docs folder?

**Comment by henriquesqs** [comment]
> Could you please place this new doc under the docs folder?

Done @fernandovgs :)

**Review by fernandovgs — APPROVED** [review]

**Comment by fernandovgs** [comment]
Nice!

**Review by lucasvianav — APPROVED** [review]

**Review by joaofavoretti — APPROVED** [review]

**Pull request merged**
