### PR TITLE
Fix snake horizontal movement

### LINKED ISSUE #156: Fix the snake horizontal vs vertical inconsistent speed
## Description
The movement of the snake clearly seems to be inconsistent. The snake speed horizontally is significantly slow in comparison with the snake vertical movement. 
This issue can clearly disturb the player experience of playing the game.

## How it should be
The speed of the snake should be the same (or close to), horizontally and vertically.

## Alternatives 
Seems that the snake moves one character by time, horizontally and vertically. 
Since the distance between two characters side-by-side in the same line is significantly smaller than two characters side-by-side in the same column, the snake could move one blank line more when moving horizontally.

### PR DESCRIPTION
**Pull request by yuji-teoi**
Closes #156 

This PR proposes the following changes:
*Fix horizontal movement of the snake to properly move at the same distance horizontally and vertically.
*Change some variables related to these movements, including the position of the snake and the power block.

### CODE REVIEW

**Comment by LeoFonsecaP** [comment]
Looks good to me. Not sure how many approvals we need before closing. After its merged, I´ll see if it fixed the energy glitch.

**Review by LeoFonsecaP — APPROVED** [review]

**Comment by yuji-teoi** [comment]
@LeoFonsecaP thanks.
I was waiting for this approval for so long...
If all gets working well, you can press the Merge pull request button

**Comment by LeoFonsecaP** [comment]
> @LeoFonsecaP thanks. I was waiting for this approval for so long... If all gets working well, you can press the Merge pull request button

Not sure if I´m doing something wrong, but nothing changed for me. Still no energy and the movement is faster vertically.

**Comment by yuji-teoi** [comment]
> 

When I do a modification on the code, I just tipe make and then sudo make install , on the Terminal.
You can also check if you are in the properly 'feature/#154' branch on git.

**Comment by LeoFonsecaP** [comment]
> > 
> 
> When I do a modification on the code, I just tipe make and then sudo make install , on the Terminal. You can also check if you are in the properly 'feature/#154' branch on git.

Oh, it worked. But the starting energy is at the border for me. The movement is fixed, if you want we can merge for fixed movement and then fix the energy issue.
But that´s the first time I can see the energy thing.

**Comment by yuji-teoi** [comment]
> 

Well, i tested the game again, changing absolutely nothing on the code and the first energy block is not spawning at all ...
But since the problem described on #173 is not related to my code, I think we can work on the two problems separately as you mentioned

**Pull request merged**
