### PR TITLE
update README.md Controls and Contributing sections

### LINKED ISSUE #8: README.md Controls and Contributing sections could be slightly improved
Some buttons in the _Controls_ section are shown in lowercase and others in uppercase.
In the _Contribute to this project_ section, there's no link to the CONTRIBUTING.md document, only a text informing of its location.

### PR DESCRIPTION
**Pull request by Float07**
This PR fixes #8 

The lines in the _Controls_ section were a little inconsistent. I tried to make them follow a simple pattern. They have now a more elegant look (in my opinion).
In the _Contribute to this project_ section I added a hyperlink to the CONTRIBUTING.md file where it would just the location of the file.

### CODE REVIEW

**Comment by Float07** [comment]
Also can someone confirm to me that + decreases the speed and - increases it? This seems counter-intuitive but I don't know if the README is wrong or if this is really the control schema.

**Review by jufantozzi — APPROVED** [review]

**Comment by math-araujo** [comment]
> Also can someone confirm to me that + decreases the speed and - increases it? This seems counter-intuitive but I don't know if the README is wrong or if this is really the control schema.

I think this simply isn't implemented yet. I agree that this control schema is counter-intuitive. Since this functionality isn't implemented anyway, we could use this as opportunity to improve the control schema (and use + for increase and - for decrease speed, respectively) and update the README.md before we code this part.  What do you think?

**Comment by Float07** [comment]
> I think this simply isn't implemented yet. I agree that this control schema is counter-intuitive. Since this functionality isn't implemented anyway, we could use this as opportunity to improve the control schema (and use + for increase and - for decrease speed, respectively) and update the README.md before we code this part. What do you think?

I was thinking the same thing! Will make these changes right away!

**Review by math-araujo — APPROVED** [review]
LGTM! :)

**Pull request merged**
