### PR TITLE
New template for issues

### LINKED ISSUE #22: Missing template for issues
In addition to #17, a template for issues would also be useful to help everyone raise more comprehensive issues with a good description of what the problem/suggestion is and any possible steps that may be taken to solve it, especially when involving the actual code. 

It should be a very similar (and easy) PR to #17's. Suggestion: I liked how #13 was formatted.

Feel free to discuss about it here :)

_Originally posted by @lucasvianav in https://github.com/courselab/snaskii21/issues/17#issuecomment-965804067_

### PR DESCRIPTION
**Pull request by Yudiaramos**
PR template (fixes issue #22)

This feature provides a more user friendly visualization when creating new issues, fixing problem discussed on issue #22 . The feature may be improved with time as new issue labels are created.

It contains 7 files: 1 being the main list of issues you can select, and the other 6 being the issues automatically created (containing labels).

### CODE REVIEW

**Comment by lucasvianav** [comment]
I'm not familiar with templates and settings, what does this do exactly? Does it only add a button similar to what you mentioned in #22 or does it actually provide a template after you create an issue, like the one we have for PRs?

**Review by lucasvianav — CHANGES_REQUESTED** [review]
In the description you should include something like in the PR template ("Fixes #22") so it'll link the issue to the PR and close it whenever this gets merged.

**Comment by Yudiaramos** [comment]
Basically, when you click new issue, the request won't open directly to create a new issue, It will direct you to another page that contains a list of the types of issues that you may find. So for example, if you wan't to create a bug issue, you click on the new issue button, and then you search on the list the "Bug Issue" option, when you click it, it will finally direct you to the new issue page and it will already have the bug label.

It is a pretty simple template, but it'll help newcommers who don't really know the github interface to create issues easily.

This will be more of buttons than a readme.md type of template, but I believe we could also create a template for a more detailed explaination of how the issues will be not only made but also dealt with.

**Comment by lucasvianav** [comment]
I see. I like it but I think it's also useful to have an actual template. What do you think? 

Could be something simple just outlining some topics, maybe like:

## Problem Description

...
## Expected Result

...

## Possible Cause

...

## Possible Solutions

...

**Comment by Yudiaramos** [comment]
I didn't think of that! I'll make some changes and then i'll get back to you, so you can see how it's looking. How's that sound?

**Comment by Yudiaramos** [comment]
Hey, I just made a new commit with the changes. I've added new texts to the issue description so it will look like this: 
## What do you believe the expected behavior is
A clear and concise description of what you expected to happen.

## Relevant screenshots
If applicable, add screenshots to help explain your problem.

## Additional context
Add any other context about the problem here.

#

What do you think?

**Review by lucasvianav — APPROVED** [review]
I like it!

**Pull request merged**
